<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PasienSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        $data = [
            [
                'nama'                          => 'Budi Santoso',
                'usia'                          => 25,
                'demam_pagi'                    => 'Demam Sedang',
                'demam_sore'                    => 'Demam Tinggi',
                'sakit_kepala'                  => 1,
                'nyeri_otot'                    => 1,
                'mual'                          => 1,
                'muntah'                        => 0,
                'nyeri_perut'                   => 1,
                'diare'                         => 0,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 1,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '2001-04-12',
                'jenis_kelamin'                 => 'L',
                'telepon'                       => '081234567890',
                'alamat'                        => 'Jl. Merdeka No. 10, Jakarta',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Siti Aminah',
                'usia'                          => 12,
                'demam_pagi'                    => 'Demam Ringan',
                'demam_sore'                    => 'Demam Sedang',
                'sakit_kepala'                  => 1,
                'nyeri_otot'                    => 0,
                'mual'                          => 1,
                'muntah'                        => 1,
                'nyeri_perut'                   => 0,
                'diare'                         => 1,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 0,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '2014-08-22',
                'jenis_kelamin'                 => 'P',
                'telepon'                       => '082345678901',
                'alamat'                        => 'Jl. Mawar No. 4, Surabaya',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Andi Wijaya',
                'usia'                          => 34,
                'demam_pagi'                    => 'Tidak Demam',
                'demam_sore'                    => 'Demam Ringan',
                'sakit_kepala'                  => 0,
                'nyeri_otot'                    => 1,
                'mual'                          => 0,
                'muntah'                        => 0,
                'nyeri_perut'                   => 0,
                'diare'                         => 0,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 0,
                'lemas'                         => 0,
                'tanggal_lahir'                 => '1992-11-05',
                'jenis_kelamin'                 => 'L',
                'telepon'                       => '083456789012',
                'alamat'                        => 'Jl. Melati No. 15, Bandung',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Dewi Lestari',
                'usia'                          => 18,
                'demam_pagi'                    => 'Demam Tinggi',
                'demam_sore'                    => 'Hiperpireksia',
                'sakit_kepala'                  => 1,
                'nyeri_otot'                    => 1,
                'mual'                          => 1,
                'muntah'                        => 1,
                'nyeri_perut'                   => 1,
                'diare'                         => 1,
                'penurunan_kesadaran'           => 1,
                'penurunan_kesadaran_deskripsi' => 'Mengantuk berat dan sulit dibangunkan sejak pagi hari',
                'bradikardia_relatif'           => 1,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '2008-02-14',
                'jenis_kelamin'                 => 'P',
                'telepon'                       => '084567890123',
                'alamat'                        => 'Jl. Kenanga No. 8, Yogyakarta',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Eko Prasetyo',
                'usia'                          => 45,
                'demam_pagi'                    => 'Demam Ringan',
                'demam_sore'                    => 'Demam Ringan',
                'sakit_kepala'                  => 0,
                'nyeri_otot'                    => 1,
                'mual'                          => 1,
                'muntah'                        => 0,
                'nyeri_perut'                   => 0,
                'diare'                         => 0,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 0,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '1981-06-30',
                'jenis_kelamin'                 => 'L',
                'telepon'                       => '085678901234',
                'alamat'                        => 'Jl. Dahlia No. 22, Semarang',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Farida Utami',
                'usia'                          => 9,
                'demam_pagi'                    => 'Demam Sedang',
                'demam_sore'                    => 'Demam Sedang',
                'sakit_kepala'                  => 1,
                'nyeri_otot'                    => 0,
                'mual'                          => 0,
                'muntah'                        => 1,
                'nyeri_perut'                   => 1,
                'diare'                         => 1,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 0,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '2017-09-15',
                'jenis_kelamin'                 => 'P',
                'telepon'                       => '086789012345',
                'alamat'                        => 'Jl. Kamboja No. 3, Malang',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Guntur Wibowo',
                'usia'                          => 50,
                'demam_pagi'                    => 'Tidak Demam',
                'demam_sore'                    => 'Tidak Demam',
                'sakit_kepala'                  => 0,
                'nyeri_otot'                    => 0,
                'mual'                          => 0,
                'muntah'                        => 0,
                'nyeri_perut'                   => 0,
                'diare'                         => 0,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 0,
                'lemas'                         => 0,
                'tanggal_lahir'                 => '1976-03-10',
                'jenis_kelamin'                 => 'L',
                'telepon'                       => '087890123456',
                'alamat'                        => 'Jl. Anggrek No. 12, Solo',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Hani Handayani',
                'usia'                          => 28,
                'demam_pagi'                    => 'Demam Sedang',
                'demam_sore'                    => 'Demam Tinggi',
                'sakit_kepala'                  => 1,
                'nyeri_otot'                    => 1,
                'mual'                          => 1,
                'muntah'                        => 0,
                'nyeri_perut'                   => 1,
                'diare'                         => 0,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 0,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '1998-07-19',
                'jenis_kelamin'                 => 'P',
                'telepon'                       => '088901234567',
                'alamat'                        => 'Jl. Flamboyan No. 7, Denpasar',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Irfan Hakim',
                'usia'                          => 16,
                'demam_pagi'                    => 'Demam Tinggi',
                'demam_sore'                    => 'Demam Tinggi',
                'sakit_kepala'                  => 1,
                'nyeri_otot'                    => 1,
                'mual'                          => 1,
                'muntah'                        => 1,
                'nyeri_perut'                   => 0,
                'diare'                         => 1,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 1,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '2010-10-01',
                'jenis_kelamin'                 => 'L',
                'telepon'                       => '089012345678',
                'alamat'                        => 'Jl. Sakura No. 19, Medan',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Julia Perez',
                'usia'                          => 22,
                'demam_pagi'                    => 'Demam Ringan',
                'demam_sore'                    => 'Demam Sedang',
                'sakit_kepala'                  => 1,
                'nyeri_otot'                    => 0,
                'mual'                          => 1,
                'muntah'                        => 0,
                'nyeri_perut'                   => 1,
                'diare'                         => 0,
                'penurunan_kesadaran'           => 0,
                'penurunan_kesadaran_deskripsi' => null,
                'bradikardia_relatif'           => 0,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '2004-05-12',
                'jenis_kelamin'                 => 'P',
                'telepon'                       => '090123456789',
                'alamat'                        => 'Jl. Tulip No. 11, Palembang',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
            [
                'nama'                          => 'Kurniawan Dwi',
                'usia'                          => 60,
                'demam_pagi'                    => 'Demam Sedang',
                'demam_sore'                    => 'Demam Tinggi',
                'sakit_kepala'                  => 1,
                'nyeri_otot'                    => 1,
                'mual'                          => 0,
                'muntah'                        => 1,
                'nyeri_perut'                   => 1,
                'diare'                         => 1,
                'penurunan_kesadaran'           => 1,
                'penurunan_kesadaran_deskripsi' => 'Kebingungan dan disorientasi arah di sore hari',
                'bradikardia_relatif'           => 0,
                'lemas'                         => 1,
                'tanggal_lahir'                 => '1966-12-25',
                'jenis_kelamin'                 => 'L',
                'telepon'                       => '091234567890',
                'alamat'                        => 'Jl. Teratai No. 14, Makassar',
                'created_at'                    => $now,
                'updated_at'                    => $now,
            ],
        ];

        $this->db->table('pasien')->insertBatch($data);
    }
}
